export type Scholarship = {
  id: number;
  title: string;
  provider: string;
  category: "Government" | "Private";
  eligible_courses: string[];
  income_limit: number;
  deadline: string;
  description: string;
  apply_link: string;
  tags: string[];
  amount: string;
  education_level?: string;
  source_portal?: string;
};

export const sampleScholarships: Scholarship[] = [
  // --- GOVERNMENT SCHOLARSHIPS (CENTRAL & STATE) ---
  {
    id: 1,
    title: "Central Sector Scheme of Scholarship for College & University Students",
    provider: "Ministry of Education (Govt of India)",
    category: "Government",
    eligible_courses: ["Bachelors", "Masters", "Engineering", "Medical"],
    income_limit: 450000,
    deadline: "2026-10-31",
    description:
      "Prestigious central government scheme implemented through the National Scholarship Portal (NSP) to support meritorious students from low-income families pursuing regular higher education degrees.",
    apply_link: "https://scholarships.gov.in/",
    tags: ["government", "merit", "central", "nsp"],
    amount: "₹20,000 / year",
    education_level: "Undergraduate & Postgraduate",
    source_portal: "National Scholarship Portal (scholarships.gov.in)",
  },
  {
    id: 2,
    title: "AICTE Pragati Scholarship Scheme for Girl Students",
    provider: "All India Council for Technical Education (AICTE)",
    category: "Government",
    eligible_courses: ["Bachelors", "Diploma", "Engineering", "Technology"],
    income_limit: 800000,
    deadline: "2026-11-15",
    description:
      "Flagship government scheme giving financial aid of ₹50,000 per annum to young women taking admission in technical degree or diploma courses across AICTE-approved institutions.",
    apply_link: "https://www.aicte-india.org/schemes/students-development-schemes/Pragati",
    tags: ["government", "women", "stem", "aicte", "technical"],
    amount: "₹50,000 / year",
    education_level: "Technical Degree / Diploma",
    source_portal: "AICTE Portal (aicte-india.org)",
  },
  {
    id: 3,
    title: "AICTE Saksham Scholarship for Specially Abled Students",
    provider: "AICTE (Govt of India)",
    category: "Government",
    eligible_courses: ["Bachelors", "Diploma", "Engineering"],
    income_limit: 800000,
    deadline: "2026-11-15",
    description:
      "Dedicated government scheme designed to support specially-abled students with over 40% disability enrolled in technical degrees and diplomas at recognized colleges.",
    apply_link: "https://www.aicte-india.org/schemes/students-development-schemes/Saksham",
    tags: ["government", "welfare", "stem", "disability"],
    amount: "₹50,000 / year",
    education_level: "Technical Degree / Diploma",
    source_portal: "National Scholarship Portal & AICTE",
  },
  {
    id: 4,
    title: "Post-Matric Scholarship Scheme for Minorities (NSP)",
    provider: "Ministry of Minority Affairs (Govt of India)",
    category: "Government",
    eligible_courses: ["Bachelors", "Masters", "PhD", "Diploma", "Certificate"],
    income_limit: 200000,
    deadline: "2026-11-30",
    description:
      "Central government financial aid covering full course fee and monthly maintenance allowance for minority community students (Muslim, Christian, Sikh, Buddhist, Jain, Parsi).",
    apply_link: "https://scholarships.gov.in/",
    tags: ["government", "minorities", "welfare", "nsp"],
    amount: "Course Fees + ₹10,000/yr Allowance",
    education_level: "Higher Secondary & College",
    source_portal: "National Scholarship Portal (scholarships.gov.in)",
  },
  {
    id: 5,
    title: "INSPIRE Scholarship for Higher Education (SHE)",
    provider: "Department of Science and Technology (DST, Govt of India)",
    category: "Government",
    eligible_courses: ["Bachelors", "Masters"],
    income_limit: 1000000,
    deadline: "2026-12-31",
    description:
      "Top-tier science scholarship for students in the top 1% of 12th Board examinations pursuing Natural & Basic Sciences (B.Sc., B.S., Int. M.Sc.) to foster scientific research.",
    apply_link: "https://online-inspire.gov.in/",
    tags: ["government", "merit", "stem", "research"],
    amount: "₹80,000 / year (₹60k cash + ₹20k mentorship)",
    education_level: "B.Sc. / B.S. / Integrated M.Sc.",
    source_portal: "DST INSPIRE Portal (online-inspire.gov.in)",
  },
  {
    id: 6,
    title: "UGC Ishan Uday Special Scholarship for North Eastern Region",
    provider: "University Grants Commission (UGC)",
    category: "Government",
    eligible_courses: ["Bachelors", "Engineering", "Medical"],
    income_limit: 450000,
    deadline: "2026-11-30",
    description:
      "Special UGC initiative for students holding domicile of North Eastern states (Assam, Meghalaya, Manipur, Mizoram, Tripura, Nagaland, Arunachal, Sikkim) enrolled in general and professional degree courses.",
    apply_link: "https://scholarships.gov.in/",
    tags: ["government", "regional", "welfare", "ugc"],
    amount: "Up to ₹7,800 / month",
    education_level: "Undergraduate Degree",
    source_portal: "National Scholarship Portal (scholarships.gov.in)",
  },
  {
    id: 7,
    title: "State Social Welfare Post-Matric Scholarship (SC / ST / OBC / EBC)",
    provider: "State Governments & Social Welfare Departments",
    category: "Government",
    eligible_courses: ["Bachelors", "Masters", "Diploma", "Engineering", "Medical"],
    income_limit: 250000,
    deadline: "2027-01-15",
    description:
      "State social welfare departments across India offer 100% tuition reimbursement and monthly maintenance allowances to students from reserved communities.",
    apply_link: "https://scholarships.gov.in/",
    tags: ["government", "welfare", "state"],
    amount: "100% Tuition Waiver + Maintenance",
    education_level: "Post-Matric (College & Univ)",
    source_portal: "State Portals & NSP",
  },
  {
    id: 8,
    title: "Prime Minister's Scholarship Scheme (PMSS) for Central Armed Forces",
    provider: "Welfare and Rehabilitation Board (MHA, Govt of India)",
    category: "Government",
    eligible_courses: ["Bachelors", "Engineering", "Medical", "Dental", "MBA"],
    income_limit: 600000,
    deadline: "2026-12-20",
    description:
      "Encourages technical and professional education among dependent wards and widows of Central Armed Police Forces (CAPF) & Assam Rifles personnel.",
    apply_link: "https://scholarships.gov.in/",
    tags: ["government", "defence", "merit", "nsp"],
    amount: "₹3,000/month (Girls) | ₹2,500/month (Boys)",
    education_level: "Professional Degree (B.Tech, MBBS, MBA)",
    source_portal: "National Scholarship Portal (scholarships.gov.in)",
  },
  {
    id: 9,
    title: "LIC Golden Jubilee Scholarship Scheme",
    provider: "Life Insurance Corporation of India (LIC)",
    category: "Government",
    eligible_courses: ["Bachelors", "Diploma", "Engineering", "Medical"],
    income_limit: 250000,
    deadline: "2026-12-25",
    description:
      "Offers scholarships to economically weaker students who have passed Class 10/12 with at least 60% marks and are pursuing higher studies in medicine, engineering, graduation, or vocational courses.",
    apply_link: "https://licindia.in/golden-jubilee-scholarship-scheme",
    tags: ["government", "merit", "welfare", "lic"],
    amount: "₹20,000 to ₹40,000 / year",
    education_level: "UG, Diploma, Vocational Courses",
    source_portal: "LIC India Official Portal (licindia.in)",
  },

  // --- PRIVATE & CORPORATE SCHOLARSHIPS ---
  {
    id: 10,
    title: "Reliance Foundation Undergraduate & Postgraduate Scholarships",
    provider: "Reliance Foundation",
    category: "Private",
    eligible_courses: ["Bachelors", "Masters", "Engineering", "Computer Science"],
    income_limit: 1500000,
    deadline: "2026-10-15",
    description:
      "One of India's largest private scholarship initiatives, selecting 5,000 undergraduate and 100 postgraduate scholars in any stream based on aptitude, merit, and leadership potential.",
    apply_link: "https://www.reliancefoundation.org/scholarships",
    tags: ["private", "merit", "reliance", "stem"],
    amount: "Up to ₹2,00,000 (UG) / ₹6,00,000 (PG)",
    education_level: "First-Year Undergraduate & Masters",
    source_portal: "Reliance Foundation Official Portal",
  },
  {
    id: 11,
    title: "Google Generation Scholarship (APAC / India)",
    provider: "Google / Alphabet",
    category: "Private",
    eligible_courses: ["Bachelors", "Masters", "Engineering", "Computer Science"],
    income_limit: 1200000,
    deadline: "2026-12-15",
    description:
      "Awarded to female students studying computer science, computer engineering, or related technical degrees in India to cultivate diversity, technical excellence, and future leadership.",
    apply_link: "https://buildyourfuture.withgoogle.com/scholarships/generation-google-scholarship-apac",
    tags: ["private", "women", "stem", "google"],
    amount: "$2,500 (~₹2,10,000)",
    education_level: "Undergraduate / Masters in CS",
    source_portal: "Google Build Your Future Portal",
  },
  {
    id: 12,
    title: "Tata Capital Pankh Scholarship Program",
    provider: "Tata Capital",
    category: "Private",
    eligible_courses: ["Bachelors", "Diploma", "Certificate", "General Graduation"],
    income_limit: 400000,
    deadline: "2026-11-30",
    description:
      "Tata Capital's flagship CSR initiative hosted on Buddy4Study offering financial support up to ₹12,000 per year to economically underprivileged students across India.",
    apply_link: "https://www.buddy4study.com/page/tata-capital-pankh-scholarship-programme",
    tags: ["private", "tata", "welfare", "need-based"],
    amount: "Up to ₹12,000 / year",
    education_level: "Class 11, 12, Diploma, UG",
    source_portal: "Tata Capital & Buddy4Study",
  },
  {
    id: 13,
    title: "Infosys Foundation STEM Stars Scholarship",
    provider: "Infosys Foundation",
    category: "Private",
    eligible_courses: ["Bachelors", "Masters", "Engineering", "Medical"],
    income_limit: 800000,
    deadline: "2026-10-25",
    description:
      "Comprehensive four-year financial scholarship covering college tuition, accommodation, and study materials for meritorious female students enrolled in premier STEM institutions in India.",
    apply_link: "https://www.infosys.com/infosys-foundation/initiatives/education/stem-stars.html",
    tags: ["private", "women", "stem", "infosys"],
    amount: "Up to ₹1,00,000 / year (Full Tuition)",
    education_level: "B.Tech / MBBS / B.Sc STEM",
    source_portal: "Infosys Foundation Portal",
  },
  {
    id: 14,
    title: "HDFC Bank Parivartan's ECSS Programme",
    provider: "HDFC Bank",
    category: "Private",
    eligible_courses: ["Bachelors", "Masters", "Diploma", "Engineering"],
    income_limit: 600000,
    deadline: "2026-10-31",
    description:
      "Educational Crisis Support Scholarship (ECSS) by HDFC Bank providing financial grants up to ₹75,000 to students facing economic hardship or unexpected family financial crises.",
    apply_link: "https://www.buddy4study.com/page/hdfc-bank-parivartan-ecss-programme",
    tags: ["private", "hdfc", "merit", "welfare"],
    amount: "Up to ₹75,000",
    education_level: "School & College Students",
    source_portal: "HDFC Parivartan & Buddy4Study",
  },
  {
    id: 15,
    title: "Amazon Future Engineer Scholarship",
    provider: "Amazon India",
    category: "Private",
    eligible_courses: ["Bachelors", "Engineering", "Computer Science"],
    income_limit: 300000,
    deadline: "2026-11-15",
    description:
      "Prestigious initiative for female engineering students providing ₹50,000/year for 4 years, mentorship by Amazon software engineers, and fast-track internship interview opportunities.",
    apply_link: "https://www.amazonfutureengineer.in/scholarship",
    tags: ["private", "amazon", "women", "stem"],
    amount: "₹50,000 / year + Amazon Mentorship",
    education_level: "B.Tech / B.E. in Computer Science/IT",
    source_portal: "Amazon Future Engineer India Portal",
  },
  {
    id: 16,
    title: "Adobe India Women-in-Technology Scholarship",
    provider: "Adobe Systems",
    category: "Private",
    eligible_courses: ["Bachelors", "Masters", "Engineering"],
    income_limit: 1200000,
    deadline: "2026-11-20",
    description:
      "Strives to recognize and advance outstanding female students studying Computer Science and Engineering. Includes full college tuition fees and guaranteed summer internship at Adobe India.",
    apply_link: "https://www.adobe.com/careers/university/india-women-in-technology.html",
    tags: ["private", "adobe", "women", "stem"],
    amount: "Full Tuition Coverage + Adobe Internship",
    education_level: "B.Tech / Dual Degree / M.Tech",
    source_portal: "Adobe Careers University Portal",
  },
  {
    id: 17,
    title: "Siemens Scholarship Program",
    provider: "Siemens India",
    category: "Private",
    eligible_courses: ["Bachelors", "Engineering"],
    income_limit: 200000,
    deadline: "2026-10-20",
    description:
      "Offers first-year government engineering college students 100% tuition reimbursement, books allowance, laptops, soft skill training, and industry internships throughout their engineering degree.",
    apply_link: "https://www.siemens.com/in/en/company/sustainability/corporate-citizenship/siemens-scholarship-program.html",
    tags: ["private", "stem", "merit", "siemens"],
    amount: "100% Tuition Fees + Living Allowance + Laptop",
    education_level: "First-Year B.Tech / B.E. (Govt Colleges)",
    source_portal: "Siemens India Sustainability Portal",
  },
  {
    id: 18,
    title: "Kotak Kanya Scholarship",
    provider: "Kotak Education Foundation",
    category: "Private",
    eligible_courses: ["Bachelors", "Engineering", "Medical", "Law", "Architecture"],
    income_limit: 600000,
    deadline: "2026-10-31",
    description:
      "Empowers meritorious girl students from economically disadvantaged families who scored >85% in Class 12 and gained admission into professional graduation degree courses in India.",
    apply_link: "https://www.buddy4study.com/page/kotak-kanya-scholarship",
    tags: ["private", "women", "merit", "kotak"],
    amount: "₹1,50,000 / year",
    education_level: "Professional Graduation (Engg, MBBS, LLB)",
    source_portal: "Kotak Education Foundation & Buddy4Study",
  },
  {
    id: 19,
    title: "L'Oréal India For Young Women in Science Scholarship",
    provider: "L'Oréal India",
    category: "Private",
    eligible_courses: ["Bachelors", "Engineering", "Medical"],
    income_limit: 600000,
    deadline: "2026-11-10",
    description:
      "Encourages young women who passed Class 12 Science with at least 85% marks to pursue higher education in scientific fields like Pure Sciences, Engineering, Biotechnology, Medicine, and Pharmacy.",
    apply_link: "https://www.loreal.com/en/india/articles/commitments/loreal-india-for-young-women-in-science-scholarships/",
    tags: ["private", "women", "stem", "loreal"],
    amount: "Up to ₹2,50,000 for entire degree",
    education_level: "Science Graduation (B.Sc., B.Tech, MBBS)",
    source_portal: "L'Oréal India Official Commitments",
  },
  {
    id: 20,
    title: "ONGC Foundation Scholarship Scheme for Meritorious Students",
    provider: "ONGC Foundation",
    category: "Private",
    eligible_courses: ["Bachelors", "Masters", "Engineering", "Medical", "MBA"],
    income_limit: 200000,
    deadline: "2026-12-05",
    description:
      "Annual scholarship for meritorious students enrolled in first year of Engineering, MBBS, MBA, and Geophysics/Geology Master's courses, promoting equal opportunity for SC, ST, OBC, and EWS students.",
    apply_link: "https://ongcscholar.org/",
    tags: ["private", "welfare", "merit", "ongc"],
    amount: "₹48,000 / year",
    education_level: "First-Year B.Tech, MBBS, MBA, M.Sc",
    source_portal: "ONGC Scholar Portal (ongcscholar.org)",
  },
  {
    id: 21,
    title: "Aditya Birla Capital Scholarship",
    provider: "Aditya Birla Capital Foundation",
    category: "Private",
    eligible_courses: ["Bachelors", "Masters", "General Graduation"],
    income_limit: 600000,
    deadline: "2026-10-25",
    description:
      "Provides financial assistance to students across school, undergraduate, and postgraduate levels to ensure uninterrupted quality education despite economic hurdles.",
    apply_link: "https://www.buddy4study.com/page/aditya-birla-capital-scholarship",
    tags: ["private", "welfare", "aditya-birla"],
    amount: "Up to ₹60,000",
    education_level: "Undergraduate & Postgraduate",
    source_portal: "Aditya Birla Capital & Buddy4Study",
  },
  {
    id: 22,
    title: "Sitaram Jindal Foundation Scholarship Scheme",
    provider: "Sitaram Jindal Foundation",
    category: "Private",
    eligible_courses: ["Bachelors", "Masters", "Diploma", "Engineering"],
    income_limit: 400000,
    deadline: "2027-01-31",
    description:
      "Merit-cum-means scholarship for students pursuing higher education across general degree, engineering, medical, and polytechnic diploma colleges with monthly stipends.",
    apply_link: "https://www.sitaramjindalfoundation.org/scholarships.php",
    tags: ["private", "merit", "welfare"],
    amount: "Up to ₹3,200 / month",
    education_level: "Polytechnic, UG, PG, Medical",
    source_portal: "Sitaram Jindal Foundation Portal",
  },
  {
    id: 23,
    title: "Mahindra All India Talent Scholarship (MAITS)",
    provider: "K. C. Mahindra Education Trust",
    category: "Private",
    eligible_courses: ["Diploma", "Engineering"],
    income_limit: 150000,
    deadline: "2027-02-28",
    description:
      "Awarded to students from rural and economically disadvantaged backgrounds who have secured admission in government or recognized polytechnics for 3-year diploma courses.",
    apply_link: "https://www.kcmet.org/what-we-do-Scholarships-Grants.aspx",
    tags: ["private", "mahindra", "diploma", "welfare"],
    amount: "₹10,000 / year for 3 years",
    education_level: "Polytechnic Diploma Courses",
    source_portal: "KC Mahindra Education Trust Portal",
  },
];

export const yearlyApplicationStats = [
  {
    year: "2022",
    "Government": 80,
    "Tech Foundation": 120,
    "WomenEd": 90,
  },
  {
    year: "2023",
    "Government": 110,
    "Tech Foundation": 150,
    "WomenEd": 100,
    "State Govt": 40,
  },
  {
    year: "2024",
    "Government": 130,
    "Tech Foundation": 180,
    "WomenEd": 120,
    "State Govt": 60,
    "Cultural Council": 90,
  },
  {
    year: "2025",
    "Government": 150,
    "Tech Foundation": 210,
    "WomenEd": 140,
    "State Govt": 70,
    "Cultural Council": 110,
    "Entrepreneurs Org": 100,
  },
];

export const topProviders = [
  { name: "Private Tech Foundation", amount: "₹1,50,00,000", initial: "TF" },
  { name: "Global Entrepreneurs Org", amount: "₹1,20,00,000", initial: "GE" },
  { name: "Government", amount: "₹95,00,000", initial: "GO" },
  { name: "WomenEd", amount: "₹80,00,000", initial: "WE" },
];
